sudo: required
services:
  - docker

before_install:
  - docker build -t gapeevdi/front-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  gapeevdi/front-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-app"
  env: "Dockerapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-140254542102"
  bucket_path: "docker-app"
  label: "1.0.0"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY